name: flowy_graph

description: A Flutter package for building interactive node-based editors, flow diagrams, and graph visualizations with ease.
version: 0.0.1
repository: https://github.com/Ahmad0Tanveer/flowy_graph
homepage: https://github.com/Ahmad0Tanveer/flowy_graph
issue_tracker: https://github.com/Ahmad0Tanveer/flowy_graph/issues

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  vector_math: ^2.2.0

topics:
  - react-flow
  - react-flow
  - flow-builder
  - workflow
  - canvas

